### ISSUE TITLE
Not working "Delete and Block"

### ISSUE THREAD

**Issue by mdziczkowski** [vanowm/FirefoxCookiesManagerPlus#96] opened 2016-07-06 15:25 UTC
The "Delete and Block" dosn't work correctly. The selected cookie is becoming removed, but it's beeing set again after page refresh.

Additionally, while using this command, all cookies from this domain with should get blocked should be removed as well

**Comment by vanowm** [comment] 2016-07-06 15:31
I need more info. If the domain is properly added into exceptions list (tools -> exceptions) then the problem is not in CM+, blocking is done by the browser itself.

As of removing all cookies for the domain when blocked, if you would, please start a new issue, so it's easier for me to track it.

Thanks.

**Comment by mdziczkowski** [comment] 2016-07-06 15:47
@vanowm Even if it's in the exceptions, the blocked cookies aren't blocked

**Comment by vanowm** [comment] 2016-07-06 15:54
In which case is not related to CM+

Exceptions is built-in browser's feature. If you disable CM+ and block domain via exceptions window (you still can access it via browser's Tools -> Options -> Privacy -> change history to custom -> Exceptions button) and cookies still being created for that domain, then there is nothing CM+ itself can do.

**Comment by mdziczkowski** [comment] 2016-07-06 17:05
@vanowm what do you think to do that CM+ could override the build-in cokin manager? this would increase the possibilities of cookie management. else, CM+ it's only good to delete or edit cookies (however all lodt grt lost after page refresh)

**Comment by vanowm** [comment] 2016-07-13 23:24
Sorry, I don't understand the question.

P.S. and what else a cookie manager supposed to do besides displaying cookies and allowing edit/delete?

**Comment by mdziczkowski** [comment] 2016-07-14 12:35
@vanowm My suggestion is that CM+ would take over the cookies management from the browser because the way the browser mange them isn't either efficient not functioning properly

**Comment by vanowm** [comment] 2016-07-14 12:48
There is already such capability with a hidden setting (in about:config) :
extensions.cookiesmanagerplus.alwaysusecmp
set it to true and CM+ will be used as default cookie manager.

That actually revealed a bug #100 :/

Closing this issue, because I see no evidence that it's related to CM+ itself.

**Closed as completed by vanowm** 2016-07-14 12:48 UTC
Labels: Bug, Need info
