### ISSUE TITLE
UI issue, does not show cookies

### ISSUE THREAD

**Issue by iripu** [vanowm/FirefoxCookiesManagerPlus#120] opened 2016-09-12 18:27 UTC
The CookieManager+ window does not show any cookies. It does not show anything whether search field is blank or has any domain. The button after search field is also blank, no text. And in menu > Tools, the 3rd item (between Exceptions... and Options) is also blank, no text or icon.

I use FF Developer version 50.0a2 32-bit (e10s off) in Windows 8.1 core 64-bit, both en-GB.

This issue stared somewhere between FF 38 and 45. I guess it's related to Windows 8.1, not sure though.

**Comment by vanowm** [comment] 2016-09-12 19:05
Duplicate of #119

It's a bug in read-only module - it chokes when cookiesManagerPlus.json file not found in firefox profile. Will be fixed today.

**Closed as completed by vanowm** 2016-09-12 19:05 UTC
